---
title: "COVID19-Frontloading"
author: "Nima Hamedani-Raja"
date: "03/05/2020"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(gganimate)
```

# About

What is frontloading?

# Read Input data

(add links to the sources)  
(explain assumptions)

```{r Input_data}
demog <- 
    inner_join(
      read.csv("input data/death_rate_v_age.csv"), 
      read.csv("input data/num_people_v_age.csv"), 
      by = "age") %>%
  mutate(year = 0)
```


```{r Input_data checks}
demog %>% 
  ggplot(aes(x = age, y = num_people)) + 
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  ggtitle("Population Pyramid")

demog %>% 
  ggplot(aes(x = age, y = death_rate)) + 
  geom_point(colour = "blue") + 
  scale_y_log10() +
  ggtitle("Death rate v. age")

demog %>% summarise(num_death = sum(num_people*death_rate), population = sum(num_people))

demog %>% summarise(annual_death_rate = sum(num_people*death_rate) / sum(num_people))
```

# Generate next years (no change in death rate)

```{r function_next_years}

demog_next_years <- function(demog, num_years, annual_birth, corona_factor){
  demog_local <- demog
  
  for(i in (1:num_years)){
    demog_local <- 
      demog_local %>% 
      filter(year == max(year)) %>%
      mutate(death_rate = corona_factor*death_rate,
             num_people = num_people * (1-death_rate),
             num_people = num_people %>% lag(1),
             num_people = replace(num_people, is.na(num_people), annual_birth),
             year = year + 1) %>%
      rbind(demog_local)
  }
  demog_local
}
```

```{r calculate_nocrona}

demog_nocorona <- demog_next_years(demog,50,750000,1)
```

Normal years look like:
```{r nocorona_summary}

demog_nocorona_summary <- 
    demog_nocorona %>% 
    group_by(year) %>% 
    summarise(num_death = sum(num_people*death_rate), population = sum(num_people)) %>%
    mutate(annual_death_rate = num_death/population)

demog_nocorona_summary %>% 
    ggplot(aes(x = year, y =annual_death_rate)) +
    geom_point(colour = "blue")

demog_nocorona_summary %>% 
    ggplot(aes(x = year, y =population)) +
    geom_point(colour = "blue")

demog_nocorona %>% 
  filter(year <= 10) %>%
  ggplot(aes(x = age, y = num_people, colour = as.factor(year))) + 
  geom_point()

demog_nocorona %>%
  filter(year <= 10) %>%
  ggplot(aes(x = age, y = num_people, colour = as.factor(year))) +
  geom_point() +
  transition_time(year) #+
# labs(title = "Year: {frame_time}")
```

# Generate next years (1st year doubled)

```{r calculate_crona}
demog_corona <- demog_next_years(demog,1,750000,2)
demog_corona <- demog_next_years(demog_corona,1,750000,1/2)
demog_corona <- demog_next_years(demog_corona,48,750000,1)
```


```{r corona_summary}
#### time-series summaries

demog_corona_summary <- 
    demog_corona %>% 
    group_by(year) %>% 
    summarise(num_death = sum(num_people*death_rate), population = sum(num_people)) %>%
    mutate(annual_death_rate = num_death/population)


demog_corona_summary %>% 
    ggplot(aes(x = year, y =annual_death_rate)) +
    geom_point(colour = "blue")

demog_corona_summary %>% 
    ggplot(aes(x = year, y =population)) +
    geom_point(colour = "blue")

demog_corona %>%
  filter(year <= 10) %>%
  ggplot(aes(x = age, y = num_people, colour = as.factor(year))) +
  geom_point()

demog_corona %>%
  # filter(year <= 10) %>%
  ggplot(aes(x = age, y = num_people, colour = as.factor(year))) +
  geom_point() +
  transition_time(year) #+
# labs(title = "Year: {frame_time}")
```

# comparing the two

```{r comparing}

#### Comparing corona and no-corona


demog_summary <- 
    rbind(demog_corona_summary %>% mutate(corona = "YES"),
          demog_nocorona_summary %>% mutate(corona = "NO"))

demog_summary %>% ggplot(aes(x = year, y = population, colour = corona)) + geom_point()
demog_summary %>% ggplot(aes(x = year, y = num_death, colour = corona)) + geom_point() + geom_line() 
demog_summary %>% ggplot(aes(x = year, y = annual_death_rate, colour = corona)) + geom_point() 

demog_summary %>% 
    group_by(corona) %>%
    mutate(tot_death = cumsum(num_death)) %>%
    ggplot(aes(x = year, y = tot_death, colour = corona)) +
    geom_point()

demog_summary %>% 
    filter(year <= 20) %>%
    group_by(corona) %>%
    mutate(tot_death = cumsum(num_death)) %>%
    ggplot(aes(x = year, y = tot_death, colour = corona)) +
    geom_point() +
    geom_line()
```

# Years lost



```{r}
demog_nocorona_nobirth <- demog_next_years(demog,101,0,1)

demog_corona_nobirth <- demog_next_years(demog,1,0,2)
demog_corona_nobirth <- demog_next_years(demog_corona_nobirth,1,0,1/2)
demog_corona_nobirth <- demog_next_years(demog_corona_nobirth,99,0,1)


years_lost <- 

inner_join(demog_corona_nobirth, demog_nocorona_nobirth, by = c("age", "year")) %>% 
    group_by(year) %>% summarise(years_lost = sum(num_people.y-num_people.x))

years_lost %>% ggplot(aes(x = year, y = years_lost)) + geom_point(colour = "blue")

tot_years_lost <- years_lost %>% summarise(sum(years_lost)) %>% as.numeric()


tot_years_ahead <- demog_nocorona_nobirth %>% summarise(sum(num_people)) %>% as.numeric()
population <- demog %>% summarise(sum(num_people)) %>% as.numeric()



tot_years_ahead/tot_years_lost
tot_years_ahead/population
tot_years_lost/population


```


```{r}
(demog_corona_summary %>% filter(year == 1)  %>% select(num_death) %>% as.numeric() - 
demog_nocorona_summary %>% filter(year == 1) %>% select(num_death) %>% as.numeric() )/population

tot_years_lost/population

```


```{r}
demog_nocorona__nobirth_summary <- 
    demog_nocorona_nobirth %>% 
    group_by(year) %>% 
    summarise(num_death = sum(num_people*death_rate), population = sum(num_people)) %>%
    mutate(annual_death_rate = num_death/population)


demog_nocorona__nobirth_summary <- 
    demog_corona_nobirth %>% 
    group_by(year) %>% 
    summarise(num_death = sum(num_people*death_rate), population = sum(num_people)) %>%
    mutate(annual_death_rate = num_death/population)



demog_nocorona__nobirth_summary %>% mutate(tot_years_ahead = cumsum(population), years_ahead = tot_years_ahead/population)

```
